# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='First name', max_length=20)),
                ('lname', models.CharField(help_text='Last name', max_length=20)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('dob', models.DateField(help_text='Date of Birth')),
            ],
            options={
                'ordering': ['lname', '-dob'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='First name', max_length=20)),
                ('lname', models.CharField(help_text='Last name', max_length=20)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('dob', models.DateField(help_text='Date of Birth')),
            ],
            options={
                'ordering': ['lname', '-dob'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='First name', max_length=20)),
                ('lname', models.CharField(help_text='Last name', max_length=20)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('dob', models.DateField(help_text='Date of Birth')),
                ('ssn', models.CharField(help_text='Social Security Number', max_length=9)),
                ('address', models.TextField(help_text='Address', max_length=40)),
                ('city', models.CharField(help_text='City', max_length=20)),
                ('zip', models.CharField(help_text='Zip Code', max_length=5)),
            ],
            options={
                'ordering': ['lname', '-dob', 'ssn'],
            },
        ),
    ]
