# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170305_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofileinfo',
            name='emergency_contact_email',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'xxxx@yyyy.zzz'.", regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')]),
        ),
        migrations.AddField(
            model_name='patientprofileinfo',
            name='emergency_contact_first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofileinfo',
            name='emergency_contact_last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientprofileinfo',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofileinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patientprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientregisterinfo',
            name='email',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'xxxx@yyyy.zzz'.", regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')]),
        ),
    ]
